name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  built_collection: ^5.0.0
  built_value: ^8.0.0
  js: ^0.6.3
  worker_bee:
    path: ../packages/worker_bee

dependency_overrides:
  worker_bee:
    path: ../packages/worker_bee

dev_dependencies:
  build_runner: ^2.0.0
  built_value_generator: ^8.1.4
  build_web_compilers: ^3.2.2
  lints: ^1.0.0
  test: ^1.16.0
  worker_bee_builder:
    path: ../packages/worker_bee_builder
