name: worker_bee_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  analyzer: ^3.0.0
  build: ^2.2.1
  source_gen: ^1.2.1
  worker_bee:
    path: ../worker_bee

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
