name: flutter_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.3
  worker_bee:
    path: ../../packages/worker_bee

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  worker_bee_builder:
    path: ../../packages/worker_bee_builder

flutter:
  uses-material-design: true
