[package]
name = "native_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
base64 = "0.13.0"
wasm-bindgen = "0.2.78"

[build-dependencies]
cbindgen = "0.20"