sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - test:
      - test: -p chrome
      - test: -p firefox
  # TODO: Safari tests cannot be run in CI
  # https://github.com/dart-lang/test/issues/1253
  # - unit_test_safari:
  #     - command: tool/test.sh -p safari
  #       os:
  #         - macos
