name: worker_bee
description: Cross-platform isolated worker runtime
version: 0.4.2
homepage: https://github.com/dnys1/worker_bee
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  async: ^2.8.2
  aws_common:
    hosted: https://pub.dillonnys.com
    version: ^0.1.6
  built_collection: ^5.1.1
  built_value: ^8.0.0
  collection: ^1.16.0
  js: ^0.6.3
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.0.0
  built_value_generator: ^8.0.0
  test: ^1.16.0
