name: worker_bee
description: Cross-platform isolated worker runtime
version: 0.2.0
homepage: https://github.com/dnys1/worker_bee
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  async: ^2.8.2
  built_value: ^8.0.0
  js: ^0.6.3
  meta: ^1.7.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  amplify_lints: ^1.0.0
  test: ^1.16.0
