// Generated by dart2js (NullSafetyMode.sound, no-legacy-javascript, new-holders, csp), the Dart to JavaScript compiler version: 2.15.0.
self.$__dart_deferred_initializers__ = self.$__dart_deferred_initializers__ || Object.create(null);
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A = {
    printString(string) {
      if (typeof dartPrint == "function") {
        dartPrint(string);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(string);
        return;
      }
      if (typeof window == "object")
        return;
      if (typeof print == "function") {
        print(string);
        return;
      }
      throw "Unable to print message: " + String(string);
    },
    callMe() {
      A.printString("Hello, world!");
    }
  };
  hunkHelpers.setFunctionNamesIfNecessary([A]);
  A = hunkHelpers.updateHolder(holdersList[3], A);
  var typesOffset = hunkHelpers.updateTypes([]);
};

$__dart_deferred_initializers__["bSTQ/lWA4kWZKQdhk567qL+zcYo="] = $__dart_deferred_initializers__.current

//# sourceMappingURL=main.js_1.part.js.map
