sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - group:
          - command: tool/test.sh
          - command: tool/test.sh -p chrome
