sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - group:
          - command: dart run build_runner build --delete-conflicting-outputs
          - test:
      - command: tool/test.sh -p chrome
      - command: tool/test.sh -p firefox
  - unit_test_safari:
      - command: tool/test.sh -p safari
        os:
          - macos
