# Created with package:mono_repo v6.2.2
name: Dart Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.2.2
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Dart dev; PKGS: example, packages/e2e_test, packages/worker_bee, packages/worker_bee_builder; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example-packages/e2e_test-packages/worker_bee-packages/worker_bee_builder;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example-packages/e2e_test-packages/worker_bee-packages/worker_bee_builder
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: example_pub_upgrade
        name: example; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example
        run: dart pub upgrade
      - name: "example; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_pub_upgrade.conclusion == 'success'"
        working-directory: example
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "example; dart analyze --fatal-infos ."
        if: "always() && steps.example_pub_upgrade.conclusion == 'success'"
        working-directory: example
        run: dart analyze --fatal-infos .
      - id: packages_e2e_test_pub_upgrade
        name: packages/e2e_test; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: dart pub upgrade
      - name: "packages/e2e_test; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_e2e_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/e2e_test; dart analyze --fatal-infos ."
        if: "always() && steps.packages_e2e_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: dart analyze --fatal-infos .
      - id: packages_worker_bee_pub_upgrade
        name: packages/worker_bee; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: dart pub upgrade
      - name: "packages/worker_bee; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_worker_bee_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/worker_bee; dart analyze --fatal-infos ."
        if: "always() && steps.packages_worker_bee_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: dart analyze --fatal-infos .
      - id: packages_worker_bee_builder_pub_upgrade
        name: packages/worker_bee_builder; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: dart pub upgrade
      - name: "packages/worker_bee_builder; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_worker_bee_builder_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/worker_bee_builder; dart analyze --fatal-infos ."
        if: "always() && steps.packages_worker_bee_builder_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: dart analyze --fatal-infos .
  job_003:
    name: "analyze_and_format; Dart stable; PKGS: example, packages/e2e_test, packages/worker_bee, packages/worker_bee_builder; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:example-packages/e2e_test-packages/worker_bee-packages/worker_bee_builder;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:example-packages/e2e_test-packages/worker_bee-packages/worker_bee_builder
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: example_pub_upgrade
        name: example; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example
        run: dart pub upgrade
      - name: "example; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_pub_upgrade.conclusion == 'success'"
        working-directory: example
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "example; dart analyze --fatal-infos ."
        if: "always() && steps.example_pub_upgrade.conclusion == 'success'"
        working-directory: example
        run: dart analyze --fatal-infos .
      - id: packages_e2e_test_pub_upgrade
        name: packages/e2e_test; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: dart pub upgrade
      - name: "packages/e2e_test; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_e2e_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/e2e_test; dart analyze --fatal-infos ."
        if: "always() && steps.packages_e2e_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/e2e_test
        run: dart analyze --fatal-infos .
      - id: packages_worker_bee_pub_upgrade
        name: packages/worker_bee; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: dart pub upgrade
      - name: "packages/worker_bee; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_worker_bee_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/worker_bee; dart analyze --fatal-infos ."
        if: "always() && steps.packages_worker_bee_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee
        run: dart analyze --fatal-infos .
      - id: packages_worker_bee_builder_pub_upgrade
        name: packages/worker_bee_builder; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: dart pub upgrade
      - name: "packages/worker_bee_builder; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_worker_bee_builder_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/worker_bee_builder; dart analyze --fatal-infos ."
        if: "always() && steps.packages_worker_bee_builder_pub_upgrade.conclusion == 'success'"
        working-directory: packages/worker_bee_builder
        run: dart analyze --fatal-infos .
